library(ggplot2)
library(exactRankTests)
library(BSDA)
souperb <- c(5,3,2,1,4,3,5,1,5,2,3,4,2,1,3)
opsys <- data.frame(
        M = c(9,8,5,3,6,10,4,2,8,7),
        W = c(7,6,8,2,9,5,1,4,7,10)
)
SIGN.test(souperb, md = 3, alternative = "less")
attach(opsys)
wilcox.exact(M, W, paired = TRUE, conf.int = TRUE)
library(vioplot)
par(mfrow=c(2,1))
vioplot(opsys$W, horizontal = TRUE, col = "grey", main = "Distribution of Operating System W")
vioplot(opsys$M, horizontal = TRUE, col = "grey", main = "Distribution of Operating System M")
